function formatDate(d) {
  if (!d) return null;
  const date = d instanceof Date ? d : new Date(d);
  return Number.isNaN(date.getTime()) ? null : date.toISOString().slice(0, 10);
}

function formatTimestamp(d) {
  if (!d) return null;
  const date = d instanceof Date ? d : new Date(d);
  return Number.isNaN(date.getTime()) ? null : date.toISOString();
}

function mapCustomer(row) {
  return {
    id: row.id,
    firstName: row.first_name || "",
    lastName: row.last_name || "",
    phone: row.phone || "",
    phoneAlt: row.phone_alt || "",
    email: row.email || "",
    address: row.address || "",
    addressType: row.address_type || "",
    unitNumber: row.unit_number || "",
    city: row.city || "",
    state: row.state || "",
    zipCode: row.zip_code || "",
    vehicle: row.vehicle || { year: "", make: "", model: "", bodyType: "", vin: "", plate: "" },
    active: row.active !== false,
    deletedAt: formatTimestamp(row.deleted_at),
    createdBy: row.created_by || "System",
    updatedBy: row.updated_by || "System",
    createdAt: formatTimestamp(row.created_at),
    updatedAt: formatTimestamp(row.updated_at),
  };
}

function mapQuote(row) {
  return {
    id: row.id,
    quoteNo: row.quote_no,
    status: row.status,
    documentType: row.document_type || "WorkOrder",
    paymentType: row.payment_type || "Personal",
    callDirection: row.call_direction || "In",
    name: row.name || "",
    date: formatDate(row.date),
    zipCode: row.zip_code || "",
    longTripFee: Number(row.long_trip_fee) || 0,
    serviceArea: row.service_area !== false,
    longTripRequired: !!row.long_trip_required,
    distanceFromBase: Number(row.distance_from_base) || 0,
    customerType: row.customer_type || "Existing",
    customerId: row.customer_id,
    customerName: row.customer_name || "",
    newCustomer: row.new_customer || {},
    insuranceCompanyId: row.insurance_company_id,
    agentId: row.agent_id,
    agentName: row.agent_name || "",
    policyNumber: row.policy_number || "",
    claimNumber: row.claim_number || "",
    appointmentDate: formatDate(row.appointment_date) || "",
    startTime: row.start_time || "",
    endTime: row.end_time || "",
    vehicle: {
      year: row.vehicle_year || "",
      make: row.vehicle_make || "",
      model: row.vehicle_model || "",
      bodyType: row.vehicle_body_type || "",
      vin: row.vehicle_vin || "",
      plate: "",
    },
    glassType: row.glass_type || "",
    partNumber: row.part_number || "",
    nagsDescription: row.nags_description || "",
    glassCost: Number(row.glass_cost) || 0,
    calibrationType: row.calibration_type || "",
    damageNotes: row.damage_notes || "",
    insurance: row.insurance || {},
    discount: row.discount || { type: "Percentage", value: 0, reason: "" },
    insuranceAdjustment: row.insurance_adjustment || { amount: 0, notes: "" },
    lineItems: row.line_items || [],
    crmPhotos: row.crm_photos || [],
    customerPhotos: row.customer_photos || [],
    taxRate: Number(row.tax_rate) || 0,
    upsell: Number(row.upsell) || 0,
    commission: Number(row.commission) || 0,
    paidAmount: Number(row.paid_amount) || 0,
    cashComeback: Number(row.cash_comeback) || 0,
    customerSuggestedPrice: Number(row.customer_suggested_price) || 0,
    payment: row.payment || {},
    lostInfo: row.lost_info || {},
    intakeToken: row.intake_token || null,
    intakeTokenExpiresAt: formatTimestamp(row.intake_token_expires_at),
    intakeSentAt: formatTimestamp(row.intake_sent_at),
    intakeOpenedAt: formatTimestamp(row.intake_opened_at),
    intakeCompletedAt: formatTimestamp(row.intake_completed_at),
    intakePhotos: row.intake_photos || { driverSide: [], passengerSide: [], front: [], rear: [], damageArea: [], insuranceCard: [] },
    active: row.active !== false,
    deletedAt: formatTimestamp(row.deleted_at),
    createdBy: row.created_by || "System",
    updatedBy: row.updated_by || "System",
    createdAt: formatTimestamp(row.created_at),
    updatedAt: formatTimestamp(row.updated_at),
  };
}

function mapWorkOrder(row) {
  return {
    id: row.id,
    workOrderNo: row.work_order_no,
    quoteId: row.quote_id,
    quoteNo: row.quote_no || "",
    customerId: row.customer_id,
    customerName: row.customer_name || "",
    workOrderType: row.work_order_type || "Personal",
    phone: row.phone || "",
    email: row.email || "",
    address: row.address || "",
    vehicle: {
      year: row.vehicle_year || "",
      make: row.vehicle_make || "",
      model: row.vehicle_model || "",
      bodyType: row.vehicle_body_type || "",
      vin: row.vehicle_vin || "",
      plate: "",
    },
    insuranceCompanyId: row.insurance_company_id,
    claimNumber: row.claim_number || "",
    policyNumber: row.policy_number || "",
    distributorId: row.distributor_id,
    distributor: row.distributor || "",
    tech: row.tech || "",
    technicianId: row.technician_id,
    techAssignedAt: null,
    partNumber: row.part_number || "",
    glassType: row.glass_type || "",
    nagsDescription: row.nags_description || "",
    jobType: row.job_type || "",
    priority: row.priority || "Normal",
    laborCost: Number(row.labor_cost) || 0,
    glassCost: Number(row.glass_cost) || 0,
    totalSale: Number(row.total_sale) || 0,
    status: row.status,
    appointmentDate: formatDate(row.appointment_date) || "",
    appointmentTime: row.appointment_time || "",
    appointmentDurationMinutes: row.appointment_duration_minutes ?? 60,
    specialInstructions: row.special_instructions || "",
    techInstructions: row.tech_instructions || "",
    internalNotes: row.internal_notes || "",
    cancellationReason: row.cancellation_reason || "",
    cancelledAt: formatTimestamp(row.cancelled_at),
    payment: row.payment || { method: "", amount: 0, paid: false, cashComeback: 0, authorizationId: "" },
    paymentHistory: row.payment_history || [],
    publicToken: row.public_token || null,
    paymentToken: row.payment_token || null,
    techPhotos: row.tech_photos || [],
    active: row.active !== false,
    deletedAt: formatTimestamp(row.deleted_at),
    createdBy: row.created_by || "System",
    updatedBy: row.updated_by || "System",
    createdAt: formatTimestamp(row.created_at),
    updatedAt: formatTimestamp(row.updated_at),
  };
}

module.exports = { mapCustomer, mapQuote, mapWorkOrder, formatDate, formatTimestamp };
